server {
    listen 80;
    server_name _;

    access_log /var/log/nginx/access.log;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }

    location /health {
        access_log off;
        return 200 '{"status":"ok","service":"web-dmz"}';
        add_header Content-Type application/json;
    }

    location /nginx_status {
        stub_status on;
        access_log off;
        allow 172.99.0.0/24;
        deny all;
    }
}